In [66]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import LassoCV
from sklearn.linear_model import ElasticNetCV
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.metrics import SCORERS

## Data Initialization

In [2]:
advertising_df = pd.read_csv("../data/Advertising.csv")
advertising_df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
X = advertising_df.drop('sales', axis=1)
X

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [4]:
y = advertising_df['sales']
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

## Feature Engineering

In [5]:
polinomial_converter = PolynomialFeatures(degree=3, include_bias=False)
polinomial_converter

PolynomialFeatures(degree=3, include_bias=False)

In [6]:
poly_features = polinomial_converter.fit_transform(X)
poly_features.shape

(200, 19)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)
X_train.shape

(140, 19)

In [8]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [9]:
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [10]:
help(Ridge)

Help on class Ridge in module sklearn.linear_model._ridge:

class Ridge(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidge)
 |  Ridge(alpha=1.0, *, fit_intercept=True, copy_X=True, max_iter=None, tol=0.0001, solver='auto', positive=False, random_state=None)
 |  
 |  Linear least squares with l2 regularization.
 |  
 |  Minimizes the objective function::
 |  
 |  ||y - Xw||^2_2 + alpha * ||w||^2_2
 |  
 |  This model solves a regression model where the loss function is
 |  the linear least squares function and regularization is given by
 |  the l2-norm. Also known as Ridge Regression or Tikhonov regularization.
 |  This estimator has built-in support for multi-variate regression
 |  (i.e., when y is a 2d-array of shape (n_samples, n_targets)).
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alpha : {float, ndarray of shape (n_targets,)}, default=1.0
 |      Constant that multiplies the L2 term, controlling regula

## Model - 01 - Ridge no cross validation

In [33]:
ridge_model = Ridge(alpha=10)
ridge_model.fit(scaled_X_train, y_train)

Ridge(alpha=10)

In [34]:
test_predictions = ridge_model.predict(scaled_X_test)
test_predictions

array([13.7469803 , 19.17764   , 11.8623393 , 16.25574551,  8.92891155,
        8.04595366, 20.13320851, 16.94847676, 10.29219174, 19.78365691,
       10.31758361, 13.44077317, 12.24228062, 23.23864236, 19.12656362,
        9.748809  , 12.84361521,  9.14248129,  8.82504966, 21.46989971,
        8.25222201, 18.8110776 , 28.39227333, 25.06911066,  9.11912241,
       11.8071711 , 20.85199462,  9.31962495, 12.25122303,  9.07811198,
        9.25275556, 19.87154568, 10.55955497,  7.86818084, 17.67220132,
        9.31442423, 10.1539168 ,  9.47802944,  8.63337302, 10.76209179,
       11.63848891, 10.38883411, 10.90270005,  8.40019284, 11.35336224,
       10.3514086 ,  8.00082147, 15.27139854, 12.94761469, 22.49762978,
       10.80165407, 13.01337743, 14.82204895, 11.37354043, 11.69628953,
        7.20576885, 25.53512232, 10.41926545, 17.38798022, 15.10158819])

In [35]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.5774404204714166

In [36]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

0.8946386461319653

In [ ]:
## Model - 02 - Ridge cross validation

In [38]:
ridge_model = RidgeCV()
ridge_model.fit(scaled_X_train, y_train)

RidgeCV()

In [39]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring="neg_mean_absolute_error")
ridge_cv_model.fit(scaled_X_train, y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [40]:
ridge_cv_model.alpha_

0.1

In [29]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'positive_likelihood_ratio', 'neg_negative_likelihood_ratio', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weig

In [41]:
test_predictions = ridge_cv_model.predict(scaled_X_test)
test_predictions

array([14.25006161, 19.10205204, 12.44776087, 17.07029103,  7.93609517,
        7.10314552, 19.94990664, 17.24524365, 10.33548736, 19.85951926,
        9.37933062, 13.9569529 , 11.85445773, 23.29303451, 19.30247423,
        9.42431717, 12.42484839,  9.21704461,  8.70229329, 21.42382243,
        7.14698141, 19.35684761, 27.33199316, 24.44887898,  9.23720121,
       11.46268721, 20.47427126,  9.4597969 , 12.55070677,  8.39250566,
        8.7928193 , 19.92435249, 10.8069225 ,  7.10760344, 18.16473242,
        9.30970124, 10.54163577,  9.71377387,  7.31109512, 10.76826686,
       12.32939318, 10.34155545, 11.39134453,  7.74592784, 11.73219215,
       10.60945023,  5.74446924, 15.33163484, 13.01377062, 22.65350817,
       10.59700761, 12.94758932, 14.71822795, 12.01718014, 11.35600126,
        5.47860188, 24.96469385,  9.42600079, 17.27904849, 15.59419989])

In [42]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.42737748843643875

In [44]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions)) 
RMSE

0.6180719926971409

In [45]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [46]:
ridge_cv_model.best_score_

-0.3749223340292948

## Model - 03 - LASSO - Least absolute shrinkage and selection operator

In [60]:
lasso_cv_model = LassoCV(eps=0.001, n_alphas=100, cv=5, max_iter=1_000_000)
lasso_cv_model.fit(scaled_X_train,y_train)

LassoCV(cv=5, max_iter=1000000)

In [61]:
lasso_cv_model.alpha_

0.004943070909225833

In [62]:
test_predictions = lasso_cv_model.predict(scaled_X_test)

In [63]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.4335034618590074

In [64]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions)) 
RMSE

0.6063140748984044

In [65]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

## Model - 04 - Elestic net - L1 and L2 regularization

In [70]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps=0.001, n_alphas=100, max_iter=1_000_000)
elastic_model.fit(scaled_X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [72]:
elastic_model.l1_ratio_

1.0

In [74]:
elastic_model.alpha_

0.004943070909225833

In [80]:
test_predictions = elastic_model.predict(scaled_X_test)
test_predictions

array([14.16203485, 19.2942685 , 12.34178429, 16.97745571,  8.02340978,
        6.95799942, 20.11875833, 17.32880647, 10.43139937, 19.96174466,
        9.56959473, 13.94205676, 11.90851817, 23.35138146, 19.56656277,
        9.27838151, 12.30485359,  9.30152997,  8.56733436, 21.51633564,
        7.06650884, 19.3377222 , 27.28027149, 24.52239173,  9.17172464,
       11.60918126, 20.73841405,  9.29953525, 12.56948515,  8.40051066,
        8.56984613, 20.03587647, 10.83439653,  6.79505173, 18.18820331,
        9.48107219, 10.41803957,  9.70785725,  7.22932328, 10.85467692,
       12.85491418, 10.51648453, 11.26905127,  7.41516944, 11.54705407,
       10.42233031,  6.02782344, 15.36338733, 13.18723611, 22.67619584,
       10.4721906 , 13.01165791, 14.56684361, 11.90062303, 11.47303307,
        5.59404766, 25.06115365,  9.69468957, 17.44771723, 15.60375637])

In [81]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.4335034618590074

In [82]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions)) 
RMSE

0.6063140748984044

### Observação
1. Neste caso em particular, elastic net convergiu para um modelo Lasso.

## Hindsight !!!
Quando estiveres a modelar os dados para um problema de regressãom, podes saltar directamente para um modelo de elastic net desde que tenha um l1_ratio que percorra os valores de l1 a l2.